name: My Workflow
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dr-alberto/rewindr@v0.1.2
        with:
          # Lets rewindr redact secret values from the captured environment.
          secrets: ${{ toJSON(secrets) }}

      - name: Run broken test
        run: |
          echo "Generating critical error..."
          exit 1
