name: My Workflow
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./

      - name: Run broken test
        run: echo "Running something very important"
        # run: |
        #   echo "Generating critical error..."
        #   exit 1
